name: 'Block Settings'
type: module
description: 'Allows settings attributes block advanced.'
package: NaviTeam
# core_version_requirement: ^8 || ^9
dependencies:
  - block

# Information added by Drupal.org packaging script on 2016-03-18
version: VERSION
core_version_requirement: ^8.8 || ^9
project: 'nvt_block_settings'
datestamp: 1458306524
